FROM ubuntu:trusty

# Add R Repository for CRAN packages

RUN ls /usr/bin | grep apt-
RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

# Try replacing the standard ubuntu archive with a faster mirror
RUN sed -i.bak 's/archive.ubuntu.com/mirrors.rit.edu/' /etc/apt/sources.list

# install Haskell, R, etc.
RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    apache2 \
    cabal-install \
    ca-certificates \
    ccache \
    gdebi \
    ghc \
    git \
    libcurl4-openssl-dev \
    libmysqlclient-dev \
    libpq-dev \
    libssl-dev \
    libx11-dev \
    libxml2-dev \
    lmodern \
    mysql-client \
    wget

# Install LaTeX
# This package list was generated by running
# `apt-cache depends texlive-full` and then excluding *-doc packages
RUN apt-get install --assume-yes --no-install-recommends \
    texlive-lang-polish  \
    texlive-generic-extra  \
    psutils  \
    latex-beamer  \
    info  \
    texlive-lang-indic  \
    texlive-lang-spanish  \
    latex-sanskrit  \
    texlive-omega  \
    texlive-lang-cyrillic  \
    texlive-lang-english  \
    prosper  \
    fragmaster  \
    texlive-base  \
    texlive-lang-european  \
    latexdiff  \
    latex-xcolor  \
    texlive-lang-african  \
    texlive-math-extra  \
    texlive-metapost  \
    texlive-lang-portuguese  \
    texlive-science  \
    tex4ht  \
    texlive-fonts-extra  \
    texlive-lang-italian  \
    dvidvi  \
    texlive-extra-utils  \
    texlive-luatex  \
    texlive-bibtex-extra  \
    latex-cjk-all  \
    texlive-latex-base  \
    texlive-font-utils  \
    texlive-fonts-recommended  \
    xindy  \
    texlive-pstricks  \
    lmodern  \
    texlive-lang-french  \
    texlive-xetex  \
    purifyeps  \
    latexmk  \
    texlive-lang-german  \
    lacheck  \
    texlive-lang-arabic  \
    texlive-plain-extra  \
    cm-super  \
    feynmf  \
    chktex  \
    tipa  \
    texlive-latex-recommended  \
    texlive-binaries  \
    texlive-music  \
    texlive-generic-recommended  \
    texlive-formats-extra  \
    texlive-humanities  \
    texlive-latex-extra  \
    texlive-publishers  \
    texlive-games  \
    pgf  \
    tex-gyre  \
    texlive-lang-greek  \
    texinfo  \
    context  \
    dvipng  \
    lcdf-typetools  \
    texlive-pictures  \
    texlive-lang-czechslovak  \
    texlive-lang-cjk  \
    t1utils  \
    texlive-lang-other

# install pandoc and put it on PATH
RUN cabal update
RUN cabal install pandoc
RUN cabal install pandoc-citeproc
ENV PATH /root/.cabal/bin:$PATH

# Install R packages
RUN apt-get build-dep --assume-yes r-cran-rgl
RUN mkdir ~/dependencies
COPY r-packages.R /tmp/
RUN R --vanilla -f /tmp/r-packages.R

# The container can now take two parameters. The R script to run in order to render
#   the manuscript, and the .Rmd file to be rendered
# WORKDIR /vagrant
# CMD ["R"]
